$ cat Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
    config.vm.define :client do |jeannebm|
      jeannebm.vm.host_name = "JeanneBM"
      jeannebm.vm.network "private_network", ip: "192.168.100.10"
      jeannebm.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true 
      jeannebm.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
#      jeannebm.vm.provision "shell", path: "start.sh"
      jeannebm.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "2048"]
          vb.customize ["modifyvm", :id, "--cpus", "3"]
      end 
    end
end
